---
##
# Add a new solr core.
#
# core_name: The core name.
#  eg: beautyhammer
#
- hosts: all
  sudo: yes

  vars_prompt:
    core_name: "Whats the name of the core you'd like to build? (ex: elccs_dd, dor2_dd)"

  tasks:

    - name: Copy the core
      action: command cp -R /var/solr/collection1 /var/solr/{{ core_name }}

    - name: Update the core.properties
      action: lineinfile dest=/var/solr/{{ core_name }}/core.properties regexp=^name line=name={{ core_name }}

    - name: Give the new core to solr.
      action: "command chown -R solr:solr /var/solr/{{ core_name }}"
