---
##
# Delete a solr core.
#
# core_name: The core name.
#  eg: beautyhammer
#
- hosts: all
  sudo: yes

  vars_prompt:
    - name: core_name
      prompt: "What's the name of the core you want to delete?"
      private: no

  tasks:
    - name: Delete the core using the REST interface
      action: command curl "http://localhost:8983/solr/admin/cores?action=UNLOAD&core={{ core_name }}&deleteInstanceDir=true"

    - name: Restart Solr.
      action: service name=solr state=restarted sleep=5

    - name: Remove the core
      action: file path=/var/solr/{{ core_name }} state=absent
